import React, { createContext, useState, useContext, useEffect } from 'react';

const translations = {
    ENG: {
        home: 'Home',
        dashboard: 'Dashboard',
        profile: 'Profile',
        createCapsule: 'Create Capsule',
        discover: 'Discover',
        logout: 'LOGOUT',
        createCapsuleTitle: "CREATE NEW CAPSULE",
        photo: "Photo",
        note: "Note",
        group: "Group",
        createNew: "Create New",
        failedToFetchCapsules: 'Failed to fetch capsules',
        untitledCapsule: 'Untitled Capsule',
        noDescription: 'No description',
        loadingCapsules: 'Loading capsules...',
        error: 'Error',
        memoryCapsuleTimeline: 'Memory Capsule Timeline',
        all: 'All',
        owner: 'owner',
        shared: 'shared',
        noCapsules: 'No memory capsules found. Create one to get started!',
        addNew: 'Add New',
        planAhead: 'plan ahead',
        createMemoryPoint: 'Create Memory Point',
        capsuleDistribution: 'CAPSULE DISTRIBUTION',
        calendarView: 'CALENDAR VIEW',
        memoryTimeline: 'Memory timeline',
        gallery: 'GALLERY',
        viewAllPhotos: 'View all photos',
        settings: 'SETTINGS',
        customizeApp: 'Customize app',
        friendsCapsules: "FRIENDS' CAPSULES",
        loadingFriendsData: "Loading friends data...",
        failedToFetchFriends: "Failed to fetch friends data",
        authTokenNotFound: "Authentication token not found",
        noFriendsFound: "No friends found. Start by adding some friends!",
        inviteFriends: "Add Friends",
        capsules: "capsules",
        commented: 'commented on',
        created: 'created',
        added: 'added to',
        modified: 'modified',
        deleted: 'deleted',
        viewed: 'viewed',
        recentActivity: 'RECENT ACTIVITY',
        failedToLoadActivity: 'Failed to load recent activity',
        noRecentActivity: 'No recent activity',
        you: 'You',
        viewAllActivity: 'View All Activity',
        commentedOn: 'commented on',
        title: 'TITLE',
        description: 'DESCRIPTION',
        uploadImages: 'Upload Images',
        chooseImages: 'Choose Images',
        setTimeDate: 'Set Date for Capsule Opening',
        addCommentToImage: 'Add Comment to Image',
        addCommentHere: 'Add your comment here...',
        cancel: 'Cancel',
        saveComment: 'Save Comment',
        vision: 'VISION',
        shareThoughts: 'Share your thoughts, expectations, or considerations for this time capsule...',
        privacySettings: 'PRIVACY SETTINGS',
        private: 'Private',
        friendsOnly: 'Friends Only',
        public: 'Public',
        previous: 'Previous',
        next: 'Next',
        saveCapsule: 'Save Capsule',
        titleAndDescription: 'TITLE AND DESCRIPTION',
        images: 'IMAGES',
        timeAndDate: 'OPENING DATE',
        imageAddons: 'IMAGE ADDONS',
        privacy: 'PRIVACY',
        capsuleDesign: 'CAPSULE DESIGN',
        preview: 'PREVIEW',
        sharing: 'SHARING',
        beginMemoryJourney: 'Begin Your Memory Preservation Journey',
        startDocumenting: 'Start documenting your life story today and create connections with your future self.',
        createFirstCapsule: 'Create Your First Capsule',
        yourMemories: 'Your Memories,',
        yourWay: 'Your Way',
        personalizeDigitalCapsules: 'Personalize your digital capsules with flexible options tailored to your individual needs',
        personal: 'Personal',
        family: 'Family',
        friends: 'Friends',
        personalGrowthJourney: 'Personal Growth Journey',
        documentAchievements: 'Document your achievements, reflections, and milestones in a structured way. Set personal capsules to open on significant dates in your future, creating a timeline of your development and growth.',
        setGoals: 'Set goals and revisit them years later',
        createPrivateJournals: 'Create private journals and reflections',
        trackJourney: 'Track your journey with customizable milestones',
        familyHeritagePreservation: 'Family Heritage Preservation',
        createSharedCapsules: 'Create shared capsules with family members to preserve your collective heritage. Document traditions, stories, and special moments to pass down through generations.',
        recordFamilyStories: 'Record family stories and histories',
        collaborateOnFamily: 'Collaborate on family milestone documentation',
        createTimeCapsules: 'Create time capsules for future generations',
        friendGroupMemories: 'Friend Group Memories',
        buildSharedCapsules: 'Build shared capsules with friends to document your adventures together. Create collaborative collections that strengthen your bond and preserve your shared experiences.',
        documentGroupTrips: 'Document group trips and adventures',
        createCapsulesForOccasions: 'Create capsules for special occasions together',
        shareAndCollectMemories: 'Share and collect memories from shared experiences',
        userTestimonial: '"Memory Capsules allows me to preserve special moments with complete control over privacy and personalization."',
        userInfo: 'Anna K. • Loyal User',
        capsule: 'Capsule',
        chooseWhoCanAccess: 'Choose who can access and view your memory capsules',
        onlyYouCanAccess: 'Only you can access',
        maximumPrivacyProtection: 'Maximum privacy protection',
        perfectForPersonalJournals: 'Perfect for personal journals',
        select: 'Select',
        recommended: 'Recommended',
        shareWithSelectedPeople: 'Share with selected people',
        selectiveSharingWithTrustedFriends: 'Selective sharing with trusted friends',
        abilityToCommentUnderFriendsCapsules: 'Ability to comment under friends capsules',
        collaborativeAdditions: 'Collaborative additions',
        shareWithTheWorld: 'Share with the world',
        publicAccessViaWebURL: 'Public access via web URL',
        communityDiscovery: 'Community discovery',
        publicComments: 'Public comments',
        preserveMomentsToday: 'Preserve your moments today, rediscover them tomorrow',
        structuredWayToDocument: 'A structured way to document your journey and maintain a connection with your future self',
        createDigitalTimeCapsule: 'Create Your Digital Time Capsule',
        documentLife: 'Document your life, maintain connections with the future, and chart your personal growth journey',
        create: 'Create',
        buildBeautifulMemoryCapsules: 'Build beautiful memory capsules with photos, videos, letters, and more.',
        seal: 'Seal',
        lockMemories: 'Lock your memories until a future date of your choosing.',
        rediscoverPastMoments: 'Rediscover your past moments when the time is right.',
        startYourJourney: 'Start Your Journey',
        privateCapsules: "Private Capsules",
        createPersonalCapsules: "Create personal capsules that only you can access, ensuring your most intimate memories remain private.",
        sharedAccess: "Shared Access",
        chooseSpecificPeople: "Choose specific people to share your capsules with, creating a more personal and meaningful connection.",
        timedRelease: "Timed Release",
        setSpecificDates: "Set specific dates for your capsules to be unlocked, creating anticipation and meaningful moments of rediscovery.",
        yourPrivacyIs: "Your Privacy Is",
        ourPriority: "Our Priority",
        completeControlDigitalFootprint: "Complete control over your digital footprint with flexible privacy options", storiesFromOur: 'Stories From Our',
        community: 'Community',
        hearHowMemoryCapsules: 'Hear how Memory Capsules has transformed the way people connect with their past and future',
        loadingTestimonials: 'Loading testimonials...',
        user: 'User',
        noReviewsAvailable: 'No reviews available at the moment.',
        shareYourExperience: 'Share Your Experience',
        closeModal: 'Close modal',
        howWouldYouRateExperience: 'How would you rate your e-capsule experience?',
        shareYourThoughtsMemories: 'Share your thoughts and memories',
        tellUsAboutExperience: 'Tell us about your experience with the e-capsule...',
        submitReview: 'Submit Review',
        editYourProfile: 'Edit Your Profile',
        firstName: 'First Name',
        lastName: 'Last Name',
        emailAddress: 'Email Address',
        tellUsAboutYourself: 'Tell us about yourself...',
        newPassword: 'New Password',
        confirmNewPassword: 'Confirm New Password',
        saveChanges: 'Save Changes',
        back: 'Back',
        confirmChanges: 'Confirm Changes',
        enterCurrentPasswordToConfirm: 'Enter your current password to confirm changes',
        profileUpdatedSuccessfully: 'Profile updated successfully!',
        correctErrorsBeforeSubmitting: 'Please correct the errors before submitting',
        failedToLoadProfile: 'Failed to load user profile',
        imageSizeExceeded: 'Image size must not exceed 2MB',
        timeCapsule: 'Time Capsule',
        thisMemoryWillUnlock: 'This memory will unlock on',
        days: 'DAYS',
        hours: 'HOURS',
        minutes: 'MINUTES',
        seconds: 'SECONDS',
        returnToProfile: 'Return to Profile',
        memoryPreview: 'Memory preview',
        photos: 'Photos',
        sealedInThisMemory: 'sealed in this memory',
        writtenMessage: 'Written message',
        specialMemoryAwaits: 'A special memory awaits',
        contentsSealed: 'Contents sealed until opening',
        readyToOpen: 'Ready to open!',
        opensIn: 'Opens in {days} days',
        findFriends: 'Find Friends',
        noUsersFound: 'No users found',
        friendRequestPending: 'Friend request pending',
        notFriendsYet: 'Not friends yet',
        addFriend: 'Add Friend',
        memories: 'Memories',
        showingPublicOnly: '(showing public only)',
        noMemoriesCreatedYet: 'No memories created yet',
        noPublicMemoriesAvailable: 'No public memories available',
        ready: 'Ready',
        daysLeft: '{days}d left',
        addComment: 'Add Comment',
        viewComments: 'View Comments',
        thisMemoryIsSealed: 'This memory is sealed until it\'s time to open it.',
        friendRequestSent: 'Friend request sent',
        failedToSendRequest: 'Failed to send friend request',
        failedToLoadUsers: 'Failed to load users',
        noBioAvailable: 'No bio available',
        alreadyFriends: 'Already Friends',
        requestSent: 'Request Sent',
        sending: 'Sending...',
        connect: 'Connect',
        searchUsers: 'Search users...',
        page: 'Page',
        of: 'of',
        notifications: 'Notifications',
        friendRequests: 'Friend Requests',
        sharedCapsules: 'Shared Capsules',
        sentYouFriendRequest: 'sent you a friend request',
        accept: 'Accept',
        decline: 'Decline',
        noFriendRequests: 'No friend requests',
        sharedCapsuleWithYou: 'shared a capsule with you',
        status: 'Status',
        noSharedCapsules: 'No shared capsules',
        someFilesSkipped: 'Some files were skipped. Only images are allowed.',
        invalidCapsuleId: 'Invalid capsule ID',
        pleaseAddAtLeastOneImage: 'Please add at least one image',
        failedToUpdateCapsuleStatus: 'Failed to update capsule status',
        failedToUploadImages: 'Failed to upload images',
        failedToResetStatus: 'Failed to reset status',
        heritageAlbum: 'Heritage Album',
        heritageAlbumDescription: 'A vintage photo album with golden accents for family memories and traditions',
        digitalChronicle: 'Digital Chronicle',
        digitalChronicleDescription: 'Futuristic interface with glowing elements and a high-tech aesthetic',
        romanticJournal: 'Romantic Journal',
        romanticJournalDescription: 'Ornate vintage journal with elegant decorations and flourishes',
        crystalVault: 'Crystal Vault',
        crystalVaultDescription: 'Geometric crystalline structure with facets that reflect your memories',
        allActivities: 'All Activities',
        titleRequired: 'Title is required',
        titleTooLong: 'Title must be less than 255 characters',
        descriptionRequired: 'Description is required',
        imagesRequired: 'At least one image is required',
        timeRequired: 'Opening time is required',
        timeMustBeFuture: 'Opening time must be in the future',
        visionRequired: 'Vision is required',
        privacyRequired: 'Please select a privacy setting',
        designRequired: 'Please select a capsule design',
        fileTypeNotSupported: 'File type not supported. Allowed types:',
        fileSizeTooLarge: 'File size must be less than',
        firstNameRequired: 'First name is required',
        firstNameMinLength: 'First name must be at least 2 characters',
        firstNameMaxLength: 'First name must be less than 50 characters',
        lastNameRequired: 'Last name is required',
        lastNameMinLength: 'Last name must be at least 2 characters',
        lastNameMaxLength: 'Last name must be less than 50 characters',
        emailRequired: 'Email is required',
        invalidEmail: 'Invalid email address',
        bioMaxLength: 'Bio must be less than 500 characters',
        passwordMinLength: 'Password must be at least 8 characters',
        passwordRequirements: 'Password must contain at least one uppercase letter, one lowercase letter, and one number',
        passwordsDoNotMatch: 'Passwords do not match',
        enterNewPassword: 'Please enter a new password',
        status_pending: 'Pending',
        status_accepted: 'Accepted',
        status_declined: 'Declined',
    },
    LAT: {
        home: 'Sākums',
        dashboard: 'Panelis',
        profile: 'Profils',
        createCapsule: 'Izveidot Kapsulu',
        discover: 'Atklāt',
        logout: 'IZIET',
        createCapsuleTitle: "IZVEIDOT JAUNU KAPSULU",
        photo: "Foto",
        note: "Piezīme",
        group: "Grupa",
        createNew: "Izveidot Jaunu",
        failedToFetchCapsules: 'Neizdevās ielādēt kapsulas',
        untitledCapsule: 'Nenosaukta Kapsula',
        noDescription: 'Nav apraksta',
        loadingCapsules: 'Ielādē kapsulas...',
        error: 'Kļūda',
        memoryCapsuleTimeline: 'Atmiņu Kapsulu Laika Skala',
        all: 'Visas',
        owner: 'īpašnieks',
        shared: 'kopīgots',
        noCapsules: 'Nav atrastas atmiņu kapsulas. Izveido jaunu, lai sāktu!',
        addNew: 'Pievienot Jaunu',
        planAhead: 'plānot',
        createMemoryPoint: 'Izveidot Atmiņu Punktu',
        capsuleDistribution: 'KAPSULU SADALĪJUMS',
        calendarView: 'KALENDĀRA SKATS',
        memoryTimeline: 'Atmiņu laika skala',
        gallery: 'GALERIJA',
        viewAllPhotos: 'Skatīt visas fotogrāfijas',
        settings: 'IESTATĪJUMI',
        customizeApp: 'Pielāgot lietotni',
        friendsCapsules: "DRAUGU KAPSULAS",
        loadingFriendsData: "Ielādē draugu datus...",
        failedToFetchFriends: "Neizdevās ielādēt draugu datus",
        authTokenNotFound: "Autentifikācijas tokens nav atrasts",
        noFriendsFound: "Nav atrasti draugi. Sāc, pievienojot dažus draugus!",
        inviteFriends: "Uzaicināt Draugus",
        capsules: "kapsulas",
        recentActivity: 'JAUNĀKĀS AKTIVITĀTES',
        failedToLoadActivity: 'Neizdevās ielādēt jaunākās aktivitātes',
        noRecentActivity: 'Nav jaunāko aktivitāšu',
        you: 'Jūs',
        viewAllActivity: 'Skatīt Visas Aktivitātes',
        commented: 'komentēji pie',
        created: 'izveidoji',
        added: 'pievienoji',
        modified: 'modificēji',
        deleted: 'izdzēsi',
        viewed: 'apskatīji',
        commentedOn: 'komentēja zem',
        title: 'NOSAUKUMS',
        description: 'APRAKSTS',
        uploadImages: 'Augšupielādēt Attēlus',
        chooseImages: 'Izvēlēties Attēlus',
        setTimeDate: 'Iestatīt Datumu Kapsulas Atvēršanai',
        addCommentToImage: 'Pievienot Komentāru Attēlam',
        addCommentHere: 'Pievienojiet savu komentāru šeit...',
        cancel: 'Atcelt',
        saveComment: 'Saglabāt Komentāru',
        vision: 'VĪZIJA',
        shareThoughts: 'Dalieties ar savām domām, cerībām vai apsvērumiem par šo laika kapsulu...',
        privacySettings: 'PRIVĀTUMA IESTATĪJUMI',
        private: 'Privāta',
        friendsOnly: 'Tikai Draugiem',
        public: 'Publiska',
        previous: 'Iepriekšējais',
        next: 'Nākamais',
        saveCapsule: 'Saglabāt Kapsulu',
        titleAndDescription: 'NOSAUKUMS UN APRAKSTS',
        images: 'ATTĒLI',
        timeAndDate: 'ATVĒRŠANAS DATUMS',
        imageAddons: 'ATTĒLU PIELIKUMI',
        privacy: 'PRIVĀTUMS',
        capsuleDesign: 'KAPSULAS DIZAINS',
        preview: 'PRIEKŠSKATĪJUMS',
        sharing: 'KOPLIETOŠANA',
        beginMemoryJourney: 'Sāc Savu Atmiņu Saglabāšanas Ceļojumu',
        startDocumenting: 'Sāc dokumentēt savu dzīvesstāstu jau šodien un veido saikni ar savu nākotnes es.',
        createFirstCapsule: 'Izveido Savu Pirmo Kapsulu',
        yourMemories: 'Tavas Atmiņas,',
        yourWay: 'Tavā Veidā',
        personalizeDigitalCapsules: 'Personalizē savas digitālās kapsulas ar elastīgām opcijām, kas pielāgotas tavām individuālajām vajadzībām',
        personal: 'Personīgi',
        family: 'Ģimene',
        friends: 'Draugi',
        personalGrowthJourney: 'Personīgās Izaugsmes Ceļojums',
        documentAchievements: 'Dokumentē savus sasniegumus, pārdomas un atskaites punktus strukturētā veidā. Iestati personiskās kapsulas, lai tās atvērtos nozīmīgos datumos tavā nākotnē, veidojot tavas attīstības un izaugsmes laika līniju.',
        setGoals: 'Izvirzi mērķus un atskatīties uz tiem pēc gadiem',
        createPrivateJournals: 'Izveido privātus žurnālus un pārdomas',
        trackJourney: 'Seko savam ceļojumam ar pielāgojamiem atskaites punktiem',
        familyHeritagePreservation: 'Ģimenes Mantojuma Saglabāšana',
        createSharedCapsules: 'Veido kopīgas kapsulas ar ģimenes locekļiem, lai saglabātu jūsu kolektīvo mantojumu. Dokumentē tradīcijas, stāstus un īpašus mirkļus, lai nodotu tos nākamajām paaudzēm.',
        recordFamilyStories: 'Ieraksti ģimenes stāstus un vēsturi',
        collaborateOnFamily: 'Sadarbojoties dokumentē ģimenes atskaites punktus',
        createTimeCapsules: 'Izveido laika kapsulas nākamajām paaudzēm',
        friendGroupMemories: 'Draugu Grupas Atmiņas',
        buildSharedCapsules: 'Veido kopīgas kapsulas ar draugiem, lai dokumentētu jūsu kopīgos piedzīvojumus. Izveido sadarbības kolekcijas, kas stiprina jūsu saikni un saglabā jūsu kopīgās pieredzes.',
        documentGroupTrips: 'Dokumentē grupas ceļojumus un piedzīvojumus',
        createCapsulesForOccasions: 'Izveido kapsulas īpašiem notikumiem kopā',
        shareAndCollectMemories: 'Dalies un kolekcionē atmiņas no kopīgām pieredzēm',
        userTestimonial: '"Atmiņu Kapsulas ļauj man saglabāt īpašus mirkļus ar pilnīgu kontroli pār privātumu un personalizāciju."',
        userInfo: 'Anna K. • Lojāls Lietotājs',
        preserveMomentsToday: 'Saglabā savus mirkļus šodien, atklāj tos no jauna rīt',
        structuredWayToDocument: 'Strukturēts veids, kā dokumentēt savu ceļojumu un uzturēt saikni ar savu nākotnes sevi',
        createDigitalTimeCapsule: 'Izveido Savu Digitālo Laika Kapsulu',
        documentLife: 'Dokumentē savu dzīvi, uzturi saikni ar nākotni un atzīmē savu personīgo izaugsmes ceļojumu',
        create: 'Izveidot',
        buildBeautifulMemoryCapsules: 'Veido skaistas atmiņu kapsulas ar fotogrāfijām, video, vēstulēm un citiem materiāliem.',
        seal: 'Noslēgt',
        lockMemories: 'Aizslēdz savas atmiņas līdz tevis izvēlētam nākotnes datumam.',
        rediscoverPastMoments: 'Atklāj savus pagātnes mirkļus, kad pienāks īstais brīdis.',
        startYourJourney: 'Sāc Savu Ceļojumu',
        privateCapsules: "Privātas Kapsulas",
        createPersonalCapsules: "Izveido personiskās kapsulas, kurām piekļūt vari tikai tu, nodrošinot, ka tavas visintīmākās atmiņas paliek privātas.",
        sharedAccess: "Kopīga Piekļuve",
        chooseSpecificPeople: "Izvēlies konkrētus cilvēkus, ar kuriem kopīgot savas kapsulas, veidojot personiskāku un jēgpilnāku saikni.",
        timedRelease: "Termiņa Atbrīvošana",
        setSpecificDates: "Iestati konkrētus datumus, kad tavas kapsulas tiks atslēgtas, radot gaidīšanas prieku un nozīmīgus atklāšanas mirkļus.",
        yourPrivacyIs: "Tavs Privātums Ir",
        ourPriority: "Mūsu Prioritāte",
        completeControlDigitalFootprint: "Pilnīga kontrole pār tavu digitālo nospiedumu ar elastīgām privātuma opcijām",
        storiesFromOur: 'Stāsti No Mūsu',
        community: 'Lietotājiem',
        hearHowMemoryCapsules: 'Uzzini, kā Atmiņu Kapsulas ir pārveidojušas veidu, kā cilvēki sazinās ar savu pagātni un nākotni',
        loadingTestimonials: 'Ielādē atsauksmes...',
        user: 'Lietotājs',
        noReviewsAvailable: 'Šobrīd nav pieejamu atsauksmju.',
        shareYourExperience: 'Dalieties Ar Savu Pieredzi',
        closeModal: 'Aizvērt logu',
        howWouldYouRateExperience: 'Kā jūs novērtētu savu e-kapsulas pieredzi?',
        shareYourThoughtsMemories: 'Dalieties ar savām domām un atmiņām',
        tellUsAboutExperience: 'Pastāstiet mums par savu pieredzi ar e-kapsulu...',
        submitReview: 'Iesniegt Atsauksmi',
        editYourProfile: 'Rediģēt Savu Profilu',
        firstName: 'Vārds',
        lastName: 'Uzvārds',
        emailAddress: 'E-pasta Adrese',
        tellUsAboutYourself: 'Pastāsti mums par sevi...',
        newPassword: 'Jauna Parole',
        confirmNewPassword: 'Apstiprini Jauno Paroli',
        saveChanges: 'Saglabāt Izmaiņas',
        back: 'Atpakaļ',
        confirmChanges: 'Apstiprināt Izmaiņas',
        enterCurrentPasswordToConfirm: 'Ievadi savu pašreizējo paroli, lai apstiprinātu izmaiņas',
        profileUpdatedSuccessfully: 'Profils veiksmīgi atjaunināts!',
        correctErrorsBeforeSubmitting: 'Lūdzu, izlabojiet kļūdas pirms iesniegšanas',
        failedToLoadProfile: 'Neizdevās ielādēt lietotāja profilu',
        imageSizeExceeded: 'Attēla izmērs nedrīkst pārsniegt 2MB',
        timeCapsule: 'Laika Kapsula',
        thisMemoryWillUnlock: 'Šī atmiņa tiks atslēgta',
        days: 'DIENAS',
        hours: 'STUNDAS',
        minutes: 'MINŪTES',
        seconds: 'SEKUNDES',
        returnToProfile: 'Atgriezties Profilā',
        memoryPreview: 'Atmiņas priekšskatījums',
        photos: 'Fotoattēli',
        sealedInThisMemory: 'noslēgti šajā atmiņā',
        writtenMessage: 'Rakstīts ziņojums',
        specialMemoryAwaits: 'Īpaša atmiņa gaida',
        contentsSealed: 'Saturs noslēgts līdz atvēršanai',
        readyToOpen: 'Gatavs atvēršanai!',
        opensIn: 'Atvērsies pēc {days} dienām',
        findFriends: 'Atrast Draugus',
        noUsersFound: 'Nav atrasts neviens lietotājs',
        friendRequestPending: 'Draudzības pieprasījums gaida atbildi',
        notFriendsYet: 'Vēl neesat draugi',
        addFriend: 'Pievienot Draugus',
        memories: 'Atmiņas',
        showingPublicOnly: '(rāda tikai publiskās)',
        noMemoriesCreatedYet: 'Vēl nav izveidotas atmiņas',
        noPublicMemoriesAvailable: 'Nav pieejamas publiskas atmiņas',
        ready: 'Gatavs',
        daysLeft: 'Atlikušas {days}d',
        addComment: 'Pievienot Komentāru',
        viewComments: 'Skatīt Komentārus',
        thisMemoryIsSealed: 'Šī atmiņa ir noslēgta līdz atvēršanas brīdim.',
        friendRequestSent: 'Draudzības pieprasījums nosūtīts',
        failedToSendRequest: 'Neizdevās nosūtīt draudzības pieprasījumu',
        failedToLoadUsers: 'Neizdevās ielādēt lietotājus',
        noBioAvailable: 'Nav pieejams apraksts',
        alreadyFriends: 'Jau Draugi',
        requestSent: 'Pieprasījums Nosūtīts',
        sending: 'Sūta...',
        connect: 'Sūtīt pieprasījumu',
        searchUsers: 'Meklēt lietotājus...',
        page: 'Lapa',
        of: 'no',
        notifications: 'Paziņojumi',
        friendRequests: 'Draugu Pieprasījumi',
        sharedCapsules: 'Kopīgotās Kapsulas',
        sentYouFriendRequest: 'nosūtīja jums drauga pieprasījumu',
        accept: 'Pieņemt',
        decline: 'Noraidīt',
        noFriendRequests: 'Nav draugu pieprasījumu',
        sharedCapsuleWithYou: 'kopīgoja ar jums kapsulu',
        status: 'Statuss',
        noSharedCapsules: 'Nav kopīgotu kapsulu',
        someFilesSkipped: 'Daži faili tika izlaisti. Atļauti tikai attēli.',
        invalidCapsuleId: 'Nederīgs kapsulas ID',
        pleaseAddAtLeastOneImage: 'Lūdzu, pievienojiet vismaz vienu attēlu',
        failedToUpdateCapsuleStatus: 'Neizdevās atjaunināt kapsulas statusu',
        failedToUploadImages: 'Neizdevās augšupielādēt attēlus',
        failedToResetStatus: 'Neizdevās atiestatīt statusu',
        heritageAlbum: 'Mantojuma Albums',
        heritageAlbumDescription: 'Vintage fotoalbums ar zelta akcentiem ģimenes atmiņām un tradīcijām',
        digitalChronicle: 'Digitālā Hronika',
        digitalChronicleDescription: 'Futuristiska saskarne ar spīdošiem elementiem un augsto tehnoloģiju estētiku',
        romanticJournal: 'Romantiskais Žurnāls',
        romanticJournalDescription: 'Greznais vintage žurnāls ar elegantām dekorācijām un ornamentiem',
        crystalVault: 'Kristāla Glabātava',
        crystalVaultDescription: 'Ģeometriska kristāla struktūra ar šķautnēm, kas atspoguļo jūsu atmiņas',
        allActivities: 'Visas aktivitātes',
        titleRequired: 'Nosaukums ir obligāts',
        titleTooLong: 'Nosaukumam jābūt īsākam par 255 rakstzīmēm',
        descriptionRequired: 'Apraksts ir obligāts',
        imagesRequired: 'Nepieciešams vismaz viens attēls',
        timeRequired: 'Atvēršanas laiks ir obligāts',
        timeMustBeFuture: 'Atvēršanas laikam jābūt nākotnē',
        visionRequired: 'Vīzija ir obligāta',
        privacyRequired: 'Lūdzu, izvēlieties privātuma iestatījumu',
        designRequired: 'Lūdzu, izvēlieties kapsulas dizainu',
        fileTypeNotSupported: 'Faila tips nav atbalstīts. Atļautie tipi:',
        fileSizeTooLarge: 'Faila izmēram jābūt mazākam par',
        firstNameRequired: 'Vārds ir obligāts',
        firstNameMinLength: 'Vārdam jābūt vismaz 2 rakstzīmes garam',
        firstNameMaxLength: 'Vārdam jābūt īsākam par 50 rakstzīmēm',
        lastNameRequired: 'Uzvārds ir obligāts',
        lastNameMinLength: 'Uzvārdam jābūt vismaz 2 rakstzīmes garam',
        lastNameMaxLength: 'Uzvārdam jābūt īsākam par 50 rakstzīmēm',
        emailRequired: 'E-pasts ir obligāts',
        invalidEmail: 'Nederīga e-pasta adrese',
        bioMaxLength: 'Aprakstam jābūt īsākam par 500 rakstzīmēm',
        passwordMinLength: 'Parolei jābūt vismaz 8 rakstzīmes garai',
        passwordRequirements: 'Parolei jāsatur vismaz viens lielais burts, viens mazais burts un viens cipars',
        passwordsDoNotMatch: 'Paroles nesakrīt',
        enterNewPassword: 'Lūdzu, ievadiet jaunu paroli',
        status_pending: 'Gaida',
        status_accepted: 'Pieņemts',
        status_declined: 'Noraidīts',
    }
};

const localeMap = {
    ENG: 'en-US',
    LAT: 'lv'
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [currentLang, setCurrentLang] = useState(() => {
        const savedLang = localStorage.getItem('preferredLanguage');
        return savedLang || 'ENG';
    });

    const changeLang = (lang) => {
        setCurrentLang(lang);
        localStorage.setItem('preferredLanguage', lang);
    };

    const t = (key) => {
        return translations[currentLang]?.[key] || key;
    };

    const getCurrentLocale = () => {
        return localeMap[currentLang] || 'en-US';
    };

    useEffect(() => {
        localStorage.setItem('preferredLanguage', currentLang);
    }, [currentLang]);

    return (
        <LanguageContext.Provider value={{ currentLang, changeLang, t, locale: getCurrentLocale() }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};